services:
  frontend:
    build:
      context: .
      args:
        NEXT_PUBLIC_STRAPI_URL: http://localhost:5001
    ports:
      - "5002:5002"
    environment:
      - NEXT_PUBLIC_STRAPI_URL=http://localhost:5001
      - STRAPI_URL=http://host.docker.internal:5001
    restart: unless-stopped
