services:
  frontend:
    build:
      context: .
      args:
        NEXT_PUBLIC_STRAPI_URL: http://localhost:1337
    ports:
      - "3000:3000"
    environment:
      - NEXT_PUBLIC_STRAPI_URL=http://localhost:1337
      - STRAPI_URL=http://host.docker.internal:1337
    restart: unless-stopped
